name: CI Process
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  behave-testing:
    #Setup of simple OS of choice. i.e. Linux
    #create VM with ubuntu OS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List repo
        run: 
          ls
      #Setup tools necessary for testing, search from marketplace
      - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.9'
        
 
 - name: pip-install-package
  # You may pin to the exact commit or the version.
  # uses: durandtibo/pip-install-package-action@9bad1fbf91b61c40b8f555f0bb19f2e742a6f0b7
  uses: durandtibo/pip-install-package-action@v0.3.1
  with:
    # The package name
    package-name: 
    # The package target version
    package-version: 
    # The python version
    python-version: 

- name: Install behave
  uses: durandt/pip-install-package-action@v3.1
  with:
    package-name: behave
    package-version: '1.2.6'
    python-version: '3.9'

- name: Run Behave Tests
  # You may pin to the exact commit or the version.
  # uses: cryptic-wizard/run-behave-tests@4b01640e49753927d5b7e5f9fbdedee02d4ca42f
  uses: cryptic-wizard/run-behave-tests@v0.4.0
  with:
    # Name of dependencies file (example: requirements.txt or example_project/requirements.txt or src/example_project/requirements.txt)
    requirements-name: # optional, default is requirements.txt
    # Path of the features parent folder if not in root (example: example_project (if example_project/features) or src/example_project/tests (if src/example_project/tests/features))
    test-path: # optional, default is 
    # Name of the output file (example: results.txt or plain.output)
    test-output-name: # optional, default is results.txt
    # Set to false to disable uploading artifact automatically
    upload-artifact: # optional, default is true
          
